### ISSUE TITLE
v0.5.7 missing com.google.vr.cardboard.Strings

### ISSUE THREAD

**Issue by robhor** [googlesamples/cardboard-java#30]
When tapping the provided configure-button inside a cardboard activity, an exception is thrown, saying that `com.google.vr.cardboard.Strings` wasn't found:

```
E/AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/vr/cardboard/Strings;
E/AndroidRuntime:     at com.google.vr.cardboard.UiUtils$ConfigureSettingsDialogFragment.onCreateDialog(UiUtils.java:160)
E/AndroidRuntime:     at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398)
E/AndroidRuntime:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973)
E/AndroidRuntime:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148)
E/AndroidRuntime:     at android.app.BackStackRecord.run(BackStackRecord.java:793)
E/AndroidRuntime:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535)
E/AndroidRuntime:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482)
E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148)
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.vr.cardboard.Strings" on path: DexPathList[[zip file "/data/app/at.robhor.cardboard-1/base.apk"],nativeLibraryDirectories=[/data/app/at.robhor.cardboard-1/lib/arm, /data/app/at.robhor.cardboard-1/base.apk!/lib/armeabi-v7a, /vendor/lib, /system/lib]]
E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime:     at com.google.vr.cardboard.UiUtils$ConfigureSettingsDialogFragment.onCreateDialog(UiUtils.java:160) 
E/AndroidRuntime:     at android.app.DialogFragment.getLayoutInflater(DialogFragment.java:398) 
E/AndroidRuntime:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:973) 
E/AndroidRuntime:     at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1148) 
E/AndroidRuntime:     at android.app.BackStackRecord.run(BackStackRecord.java:793) 
E/AndroidRuntime:     at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1535) 
E/AndroidRuntime:     at android.app.FragmentManagerImpl$1.run(FragmentManager.java:482) 
E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739) 
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95) 
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:148) 
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5417) 
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
E/AndroidRuntime: 	Suppressed: java.lang.ClassNotFoundException: com.google.vr.cardboard.Strings
E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
E/AndroidRuntime:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime:     		... 15 more
E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available
```

**Comment by dav-cz** [comment]
Thanks for the report. We're on it and we'll push a fix asap.

**Comment by capsur** [comment]
Could an issue like this by any chance convince you to make the SDK available in Maven Central? :smile:

**Comment by dav-cz** [comment]
@robhor, we just pushed 0.5.8 to fix this issue.

@capsur, yes that would be nice! it's on our todo list ;)

**Comment by robhor** [comment]
> @robhor, we just pushed 0.5.8 to fix this issue.

Thanks :smile:
