### ISSUE TITLE
Crashing on draw

### ISSUE THREAD

**Issue by ixor3d** [googlesamples/cardboard-java#8]
Hi,
I'm using a Galaxy S3 i9300 and have tested both stock 4.3 and cynogenmod 4.4.4 on the same device and I get the same error on both when trying to render a 3d object on screen.
glUseProgram: glError 1280
FATAL EXCEPTION: GLThread 908

Also when using the cardboard demo app, Windy Day crashes with the following log cat:
com.google.samples.apps.cardboarddemo E/AndroidRuntime﹕ 
FATAL EXCEPTION: GLThread 501
Process: com.google.samples.apps.cardboarddemo, PID: 10070
java.lang.RuntimeException: MoxieCommon-a No configs match configSpec
at com.motorola.moxie.common.a.a.chooseConfig(Unknown Source)
at android.opengl.GLSurfaceView$EglHelper.start(GLSurfaceView.java:1026)
at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1403)
at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1242)

Both the cardboard demo app and my app work OK on HTC one, LG G2 mini, Nexus 5.

Is there anything that can be done?

**Comment by nathanmartz** [comment]
Closing super old thread.
